import type { TaskDetail } from "../api/types";
import { recommendNextAction } from "../api/types";

interface Props {
  detail: TaskDetail | null;
  busy: boolean;
  decision?: "approving" | "rejecting";
  onApprove: (stepId: string) => Promise<void>;
  onReject: (stepId: string) => Promise<void>;
}

export function ReviewPanel({ detail, busy, decision, onApprove, onReject }: Props) {
  const step = detail?.steps[0];
  const pending = step?.status === "pending_approval";
  const recommendation = detail ? recommendNextAction(detail) : null;

  return (
    <aside className="panel panel--review">
      <div className="panel__heading">
        <div>
          <p className="eyebrow">Human gate</p>
          <h2>Review</h2>
        </div>
        <span className={`safety-indicator${pending ? " safety-indicator--pending" : ""}`}>
          {pending ? "Decision needed" : "Contained"}
        </span>
      </div>

      {/* Recommended next action */}
      {recommendation && (
        <section className="review-section review-section--recommendation">
          <h3>Next action</h3>
          <p className="recommendation-text">{recommendation}</p>
        </section>
      )}

      <section className="review-section">
        <h3>Approval</h3>
        {pending && step ? (
          <>
            <p>This simulated <strong>{step.action_type.replaceAll("_", " ")}</strong> step requires explicit approval.</p>
            <div className="approval-actions">
              <button aria-busy={decision === "approving"} className="button button--primary" disabled={busy} onClick={() => onApprove(step.id)} type="button">
                {decision === "approving" ? "Approving..." : "Approve & simulate"}
              </button>
              <button aria-busy={decision === "rejecting"} className="button button--danger" disabled={busy} onClick={() => onReject(step.id)} type="button">
                {decision === "rejecting" ? "Rejecting..." : "Reject"}
              </button>
            </div>
          </>
        ) : (
          <p className="muted">
            {detail
              ? recommendation === "Task complete"
                ? "Task is complete. No further action needed."
                : recommendation === "Rejected"
                  ? "Task was rejected. No further action is available."
                  : recommendation === "Blocked / invalid"
                    ? "Task is blocked. Review the evidence and audit trail."
                    : "No approval decision is pending."
              : "Select a task to review its gate."}
          </p>
        )}
      </section>

      <section className="review-section">
        <div className="review-section__title"><h3>Evidence timeline</h3><span>{detail?.evidence.length ?? 0}</span></div>
        <p className="evidence-disclaimer">All P0.2 evidence is generated by the contained deterministic mock runner.</p>
        {!detail?.evidence.length ? <p className="muted">No mock evidence recorded.</p> : (
          <ol className="timeline">
            {detail.evidence.map((evidence) => (
              <li key={evidence.id}>
                <span className={evidence.validation_passed ? "timeline__marker timeline__marker--pass" : "timeline__marker timeline__marker--fail"} />
                <div>
                  <strong>{evidence.validation_passed ? "Mock validation passed" : "Mock validation failed"}</strong>
                  <p>{evidence.validation_summary}</p>
                  <div className="evidence-tags">
                    <span>Exit {evidence.exit_code}</span>
                    <span>{evidence.diff ? "Diff preview" : "No diff"}</span>
                  </div>
                  <time>{new Date(evidence.created_at).toLocaleString()}</time>
                </div>
              </li>
            ))}
          </ol>
        )}
      </section>

      <section className="review-section review-section--audit">
        <h3>Audit preview</h3>
        {!detail?.audit_events.length ? <p className="muted">No audit events.</p> : (
          <ol className="audit-list">
            {detail.audit_events.map((event) => (
              <li key={event.id}>
                <code>{event.event_type}</code>
                <time>{new Date(event.created_at).toLocaleTimeString()}</time>
              </li>
            ))}
          </ol>
        )}
      </section>
    </aside>
  );
}
